import 'dart:convert';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:evangelistglobal/services/export/export_table.dart';
import 'package:evangelistglobal/services/export/register_export.dart';
import 'package:excel/excel.dart';
import 'package:flutter_test/flutter_test.dart';

/// The pupils register ([ExportLayout.register]) in PDF, Excel and Word.
void main() {
  const columns = [
    ExportColumn('Student ID'),
    ExportColumn('Full name'),
    ExportColumn('Date of birth', isDate: true),
    ExportColumn('Admission date', isDate: true),
    ExportColumn('Home address'),
  ];

  ExportTable register(int pupils) => ExportTable(
        schoolName: 'Evangelist Model School',
        title: 'Pupils Register',
        heading: 'Pupils Register - JSS 2',
        schoolAddress: '12 Main Road, Freetown',
        layout: ExportLayout.register,
        filters: const ['JSS 2', 'Active'],
        columns: columns,
        rows: [
          for (var i = 0; i < pupils; i++)
            ['EG-$i', 'Pupil $i & Co', '04/03/2012', '-', '5 Hill Road'],
        ],
        generatedAt: DateTime(2026, 10, 5, 14, 30),
      );

  String part(Uint8List zip, String name) => utf8.decode(
      ZipDecoder().decodeBytes(zip).findFile(name)!.content as List<int>);

  test('Excel: every column, real dates, frozen and filterable header', () {
    final xlsx = buildRegisterXlsx(register(3));
    final sheet = part(xlsx, 'xl/worksheets/sheet1.xml');
    expect(sheet, contains('state="frozen"'));
    expect(sheet, contains('<autoFilter ref="A6:F9"/>'));
    // 04/03/2012 as Excel day 40972, in the dd/mm/yyyy style; "-" stays text.
    expect(sheet, contains('<v>40972</v>'));
    expect(part(xlsx, 'xl/styles.xml'), contains('formatCode="dd/mm/yyyy"'));

    // Readable by another xlsx reader, with the header in row 6.
    final read = Excel.decodeBytes(xlsx).tables.values.first;
    expect(read.maxColumns, 6); // "No." + 5
    expect(read.row(5).map((c) => c?.value.toString()),
        ['No.', 'Student ID', 'Full name', 'Date of birth', 'Admission date', 'Home address']);
    expect(read.row(6)[3]?.value, isA<DateCellValue>());
    expect(read.row(6)[4]?.value.toString(), '-');
  });

  test('Word: landscape, heading row repeats, school and title on top', () {
    final docx = buildRegisterDocx(register(3));
    final doc = part(docx, 'word/document.xml');
    expect(doc, contains('w:orient="landscape"'));
    expect(doc, contains('<w:tblHeader/>'));
    expect(doc, contains('EVANGELIST MODEL SCHOOL'));
    expect(doc, contains('Pupils Register - JSS 2'));
    expect(doc, contains('Pupil 0 &amp; Co'));
    expect(part(docx, 'word/footer1.xml'), contains('Generated by Evangelist Global'));
  });

  test('PDF: a long register runs over several pages', () async {
    final pdf = await buildRegisterPdf(register(120));
    final pages =
        RegExp(r'/Type\s*/Page\b').allMatches(latin1.decode(pdf)).length;
    expect(pages, greaterThan(1));
  });

  test('other lists keep the standard layout', () {
    final t = ExportTable(
        schoolName: 'S', title: 'Teachers', columns: columns, rows: const []);
    expect(t.layout, ExportLayout.standard);
  });
}
