// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQ5st6sTYbVKVfTL7nIWREKF6m5r7rKw',
    appId: '1:874217682283:web:42b14cdd0584338aaac82e',
    messagingSenderId: '874217682283',
    projectId: 'studio-1123859931-74e89',
    authDomain: 'studio-1123859931-74e89.firebaseapp.com',
    storageBucket: 'studio-1123859931-74e89.firebasestorage.app',
    databaseURL: 'https://studio-1123859931-74e89-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDRZbAkIJ7aPXZI6f6TGG2z-fIhJ8QXpA',
    appId: '1:874217682283:android:6d19da6874693adfaac82e',
    messagingSenderId: '874217682283',
    projectId: 'studio-1123859931-74e89',
    storageBucket: 'studio-1123859931-74e89.firebasestorage.app',
    databaseURL: 'https://studio-1123859931-74e89-default-rtdb.firebaseio.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZ8p5vnA5-MH5YfDvlhqMgqickCwGmEM',
    appId: '1:874217682283:ios:1d3befe07328a1a4aac82e',
    messagingSenderId: '874217682283',
    projectId: 'studio-1123859931-74e89',
    storageBucket: 'studio-1123859931-74e89.firebasestorage.app',
    databaseURL: 'https://studio-1123859931-74e89-default-rtdb.firebaseio.com',
    iosBundleId: 'com.evangelistglobal.evangelistglobal',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZ8p5vnA5-MH5YfDvlhqMgqickCwGmEM',
    appId: '1:874217682283:ios:1d3befe07328a1a4aac82e',
    messagingSenderId: '874217682283',
    projectId: 'studio-1123859931-74e89',
    storageBucket: 'studio-1123859931-74e89.firebasestorage.app',
    databaseURL: 'https://studio-1123859931-74e89-default-rtdb.firebaseio.com',
    iosBundleId: 'com.evangelistglobal.evangelistglobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXeU6Vk6MSAjxEZtZ8lvIb-VfmuRSnqAs',
    appId: '1:874217682283:web:6907e72715a0b613aac82e',
    messagingSenderId: '874217682283',
    projectId: 'studio-1123859931-74e89',
    authDomain: 'studio-1123859931-74e89.firebaseapp.com',
    storageBucket: 'studio-1123859931-74e89.firebasestorage.app',
    databaseURL: 'https://studio-1123859931-74e89-default-rtdb.firebaseio.com',
  );
}
