import 'dart:convert';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'export_table.dart';

/// The full pupils register ([ExportLayout.register]) in PDF, Excel and Word:
/// every column, the same order and headings in all three, built to stay
/// readable with twenty-odd columns.

// Brand colours (see `AppColors`).
const _primaryHex = '2E3192';
const _stripeHex = 'F1F2FA';
const _lineHex = 'C5C8D6';
const _mutedHex = '5E6470';

String _heading(ExportTable t) => t.heading ?? t.title;

// =============================================================================
// PDF — A4 landscape, 7 pt, letterhead and column headings on every page.
// =============================================================================

final _primary = PdfColor.fromHex('#$_primaryHex');
final _stripe = PdfColor.fromHex('#$_stripeHex');
final _line = PdfColor.fromHex('#$_lineHex');
final _muted = PdfColor.fromHex('#$_mutedHex');

/// The built-in PDF font covers Latin-1 only; anything else would print as a
/// blank box, so it is replaced with "?".
String _safe(String s) =>
    String.fromCharCodes(s.runes.map((r) => r <= 0xFF ? r : 0x3F));

Future<Uint8List> buildRegisterPdf(ExportTable t) async {
  final columns = t.numberedColumns;
  final doc = pw.Document(
      title: _safe(_heading(t)),
      author: _safe(t.schoolName),
      creator: 'Evangelist Global');
  pw.ImageProvider? logo;
  try {
    if (t.logo != null) logo = pw.MemoryImage(t.logo!);
  } catch (_) {
    logo = null; // An unreadable badge is left out.
  }

  pw.Widget cell(String text, {bool header = false, bool center = false}) =>
      pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 2, vertical: 2),
        child: pw.Text(
          _safe(text),
          textAlign: center ? pw.TextAlign.center : pw.TextAlign.left,
          style: pw.TextStyle(
            fontSize: header ? 6.5 : 7,
            fontWeight: header ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: header ? PdfColors.white : null,
          ),
        ),
      );

  final rows = t.numberedRows;
  doc.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4.landscape,
    margin: const pw.EdgeInsets.fromLTRB(12, 16, 12, 14),
    header: (context) => _pdfLetterhead(t, logo),
    footer: (context) => pw.Container(
      margin: const pw.EdgeInsets.only(top: 6),
      padding: const pw.EdgeInsets.only(top: 3),
      decoration: pw.BoxDecoration(
          border: pw.Border(top: pw.BorderSide(color: _line, width: 0.5))),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Evangelist Global',
              style: pw.TextStyle(fontSize: 7, color: _muted)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(fontSize: 7, color: _muted)),
        ],
      ),
    ),
    build: (context) => [
      pw.Table(
        border: pw.TableBorder.all(color: _line, width: 0.4),
        columnWidths: {
          for (var i = 0; i < columns.length; i++)
            i: pw.FlexColumnWidth(columns[i].flex),
        },
        children: [
          // Repeated at the top of every page.
          pw.TableRow(
            repeat: true,
            decoration: pw.BoxDecoration(color: _primary),
            verticalAlignment: pw.TableCellVerticalAlignment.middle,
            children: [
              for (var i = 0; i < columns.length; i++)
                cell(columns[i].title, header: true, center: i == 0),
            ],
          ),
          for (var r = 0; r < rows.length; r++)
            pw.TableRow(
              decoration:
                  r.isOdd ? pw.BoxDecoration(color: _stripe) : null,
              children: [
                for (var i = 0; i < columns.length; i++)
                  cell(rows[r][i], center: i == 0),
              ],
            ),
        ],
      ),
      if (t.rows.isEmpty)
        pw.Padding(
          padding: const pw.EdgeInsets.all(12),
          child: pw.Center(
            child: pw.Text('No pupils match these filters.',
                style: pw.TextStyle(fontSize: 9, color: _muted)),
          ),
        ),
    ],
  ));
  return doc.save();
}

/// Badge, bold school name and address on the left; the register title,
/// filters, date printed and total on the right; a rule underneath.
pw.Widget _pdfLetterhead(ExportTable t, pw.ImageProvider? logo) => pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 6),
      padding: const pw.EdgeInsets.only(bottom: 4),
      decoration: pw.BoxDecoration(
          border: pw.Border(bottom: pw.BorderSide(color: _primary, width: 1.2))),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          if (logo != null) ...[
            pw.SizedBox(
                width: 34,
                height: 34,
                child: pw.Image(logo, fit: pw.BoxFit.contain)),
            pw.SizedBox(width: 8),
          ],
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(_safe(t.schoolName.trim().toUpperCase()),
                    style: pw.TextStyle(
                        fontSize: 13,
                        fontWeight: pw.FontWeight.bold,
                        color: _primary)),
                if (t.schoolAddress.trim().isNotEmpty)
                  pw.Text(_safe(t.schoolAddress.trim()),
                      style: const pw.TextStyle(fontSize: 8)),
              ],
            ),
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(_safe(_heading(t)),
                  style: pw.TextStyle(
                      fontSize: 11, fontWeight: pw.FontWeight.bold)),
              if (t.filters.isNotEmpty)
                pw.Text(_safe(t.filterLine),
                    style: pw.TextStyle(fontSize: 7.5, color: _muted)),
              pw.Text(_safe('Printed: ${t.dateText}   |   ${t.totalText}'),
                  style: pw.TextStyle(fontSize: 7.5, color: _muted)),
            ],
          ),
        ],
      ),
    );

// =============================================================================
// Excel — one column per field, real dates, frozen and filterable header.
// Written directly as Office Open XML (an .xlsx is a zip of XML files) so the
// sheet can have a frozen header row and filters.
// =============================================================================

/// Rows above the column headings: school name, address, title, info, blank.
const _xlsxHeaderRow = 6;

Uint8List buildRegisterXlsx(ExportTable t) {
  final columns = t.numberedColumns;
  final rows = t.numberedRows;
  final lastCol = _colName(columns.length - 1);
  final lastRow = _xlsxHeaderRow + rows.length;

  // Style ids, see _xlsxStyles.
  const sName = 1, sAddress = 2, sTitle = 3, sInfo = 4, sHead = 5;
  const sText = 6, sTextAlt = 7, sDate = 8, sDateAlt = 9, sNum = 10, sNumAlt = 11;

  final sheet = StringBuffer();
  void textCell(String ref, String text, int style) => sheet.write(
      '<c r="$ref" s="$style" t="inlineStr"><is><t xml:space="preserve">'
      '${_xmlEsc(text)}</t></is></c>');
  void bannerRow(int r, String text, int style, double height) {
    sheet.write('<row r="$r" ht="$height" customHeight="1">');
    textCell('A$r', text, style);
    sheet.write('</row>');
  }

  sheet.write('<sheetData>');
  bannerRow(1, t.schoolName.trim().toUpperCase(), sName, 24);
  bannerRow(2, t.schoolAddress.trim(), sAddress, 16);
  bannerRow(3, _heading(t), sTitle, 20);
  bannerRow(
      4,
      [
        if (t.filters.isNotEmpty) t.filterLine,
        'Printed: ${t.dateText}',
        t.totalText,
      ].join('     |     '),
      sInfo,
      16);
  sheet.write('<row r="$_xlsxHeaderRow" ht="30" customHeight="1">');
  for (var c = 0; c < columns.length; c++) {
    textCell('${_colName(c)}$_xlsxHeaderRow', columns[c].title, sHead);
  }
  sheet.write('</row>');

  for (var r = 0; r < rows.length; r++) {
    final rowNo = _xlsxHeaderRow + 1 + r;
    final alt = r.isOdd;
    sheet.write('<row r="$rowNo">');
    for (var c = 0; c < columns.length; c++) {
      final ref = '${_colName(c)}$rowNo';
      final value = rows[r][c];
      if (c == 0) {
        sheet.write('<c r="$ref" s="${alt ? sNumAlt : sNum}"><v>${r + 1}</v></c>');
        continue;
      }
      final serial = columns[c].isDate ? _excelDate(value) : null;
      if (serial != null) {
        sheet.write('<c r="$ref" s="${alt ? sDateAlt : sDate}"><v>$serial</v></c>');
      } else {
        textCell(ref, value, alt ? sTextAlt : sText);
      }
    }
    sheet.write('</row>');
  }
  sheet.write('</sheetData>');

  // "Auto-fit": as wide as the longest value (or the heading's longest word),
  // within sensible limits; long text wraps.
  final cols = StringBuffer('<cols>');
  for (var c = 0; c < columns.length; c++) {
    var width = columns[c]
        .title
        .split(' ')
        .fold<int>(0, (m, w) => w.length > m ? w.length : m)
        .toDouble();
    for (final row in rows) {
      if (row[c].length > width) width = row[c].length.toDouble();
    }
    if (columns[c].isDate) width = 10.5;
    final w = (width + 2).clamp(5.0, 40.0);
    cols.write('<col min="${c + 1}" max="${c + 1}" width="${w.toStringAsFixed(1)}" '
        'customWidth="1"/>');
  }
  cols.write('</cols>');

  final worksheet = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
      'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
      '<sheetPr><pageSetUpPr fitToPage="1"/></sheetPr>'
      '<dimension ref="A1:$lastCol$lastRow"/>'
      '<sheetViews><sheetView workbookViewId="0">'
      '<pane ySplit="$_xlsxHeaderRow" topLeftCell="A${_xlsxHeaderRow + 1}" '
      'activePane="bottomLeft" state="frozen"/>'
      '<selection pane="bottomLeft" activeCell="A${_xlsxHeaderRow + 1}" '
      'sqref="A${_xlsxHeaderRow + 1}"/></sheetView></sheetViews>'
      '<sheetFormatPr defaultRowHeight="15"/>'
      '$cols$sheet'
      '<autoFilter ref="A$_xlsxHeaderRow:$lastCol$lastRow"/>'
      '<mergeCells count="4">'
      '<mergeCell ref="A1:${lastCol}1"/><mergeCell ref="A2:${lastCol}2"/>'
      '<mergeCell ref="A3:${lastCol}3"/><mergeCell ref="A4:${lastCol}4"/>'
      '</mergeCells>'
      '<pageMargins left="0.3" right="0.3" top="0.4" bottom="0.4" header="0.2" footer="0.2"/>'
      '<pageSetup paperSize="9" orientation="landscape" fitToWidth="1" fitToHeight="0"/>'
      '</worksheet>';

  var sheetName = t.title.replaceAll(RegExp(r"[\[\]:*?/\\']"), '').trim();
  if (sheetName.isEmpty) sheetName = 'Register';
  if (sheetName.length > 31) sheetName = sheetName.substring(0, 31);
  final quoted = "'$sheetName'";
  final workbook = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
      'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
      '<sheets><sheet name="${_xmlEsc(sheetName)}" sheetId="1" r:id="rId1"/></sheets>'
      '<definedNames>'
      '<definedName name="_xlnm._FilterDatabase" localSheetId="0" hidden="1">'
      '${_xmlEsc(quoted)}!\$A\$$_xlsxHeaderRow:\$$lastCol\$$lastRow</definedName>'
      // Column headings repeat on every printed page.
      '<definedName name="_xlnm.Print_Titles" localSheetId="0">'
      '${_xmlEsc(quoted)}!\$$_xlsxHeaderRow:\$$_xlsxHeaderRow</definedName>'
      '</definedNames></workbook>';

  final archive = Archive();
  void add(String name, String xml) {
    final bytes = utf8.encode(xml);
    archive.addFile(ArchiveFile(name, bytes.length, bytes));
  }

  add('[Content_Types].xml', _xlsxContentTypes);
  add('_rels/.rels', _xlsxRootRels);
  add('xl/workbook.xml', workbook);
  add('xl/_rels/workbook.xml.rels', _xlsxWorkbookRels);
  add('xl/styles.xml', _xlsxStyles);
  add('xl/worksheets/sheet1.xml', worksheet);
  return Uint8List.fromList(ZipEncoder().encode(archive)!);
}

/// Column letters: 0 → A, 25 → Z, 26 → AA.
String _colName(int index) {
  var n = index + 1;
  var name = '';
  while (n > 0) {
    final rem = (n - 1) % 26;
    name = String.fromCharCode(65 + rem) + name;
    n = (n - 1) ~/ 26;
  }
  return name;
}

/// Excel's day number for a dd/MM/yyyy date, or null for anything else
/// (e.g. "-"), which stays text.
int? _excelDate(String value) {
  final m = RegExp(r'^(\d{2})/(\d{2})/(\d{4})$').firstMatch(value.trim());
  if (m == null) return null;
  final date = DateTime.utc(
      int.parse(m.group(3)!), int.parse(m.group(2)!), int.parse(m.group(1)!));
  return date.difference(DateTime.utc(1899, 12, 30)).inDays;
}

String _xmlEsc(String s) => s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');

const _xlsxContentTypes = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
    '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
    '<Default Extension="xml" ContentType="application/xml"/>'
    '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
    '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
    '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
    '</Types>';

const _xlsxRootRels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
    '</Relationships>';

const _xlsxWorkbookRels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
    '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
    '</Relationships>';

/// Cell styles (cellXfs), by index:
/// 0 default · 1 school name · 2 address · 3 title · 4 info line ·
/// 5 column heading · 6/7 text (plain/striped) · 8/9 date dd/mm/yyyy ·
/// 10/11 number.
const _xlsxStyles = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
    '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
    '<numFmts count="1"><numFmt numFmtId="164" formatCode="dd/mm/yyyy"/></numFmts>'
    '<fonts count="6">'
    '<font><sz val="10"/><name val="Calibri"/></font>'
    '<font><b/><sz val="16"/><color rgb="FF$_primaryHex"/><name val="Calibri"/></font>'
    '<font><sz val="10"/><name val="Calibri"/></font>'
    '<font><b/><sz val="13"/><name val="Calibri"/></font>'
    '<font><sz val="9"/><color rgb="FF$_mutedHex"/><name val="Calibri"/></font>'
    '<font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>'
    '</fonts>'
    '<fills count="4">'
    '<fill><patternFill patternType="none"/></fill>'
    '<fill><patternFill patternType="gray125"/></fill>'
    '<fill><patternFill patternType="solid"><fgColor rgb="FF$_primaryHex"/><bgColor indexed="64"/></patternFill></fill>'
    '<fill><patternFill patternType="solid"><fgColor rgb="FF$_stripeHex"/><bgColor indexed="64"/></patternFill></fill>'
    '</fills>'
    '<borders count="2">'
    '<border><left/><right/><top/><bottom/><diagonal/></border>'
    '<border><left style="thin"><color rgb="FF$_lineHex"/></left>'
    '<right style="thin"><color rgb="FF$_lineHex"/></right>'
    '<top style="thin"><color rgb="FF$_lineHex"/></top>'
    '<bottom style="thin"><color rgb="FF$_lineHex"/></bottom><diagonal/></border>'
    '</borders>'
    '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
    '<cellXfs count="12">'
    '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
    '<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>'
    '<xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>'
    '<xf numFmtId="0" fontId="3" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>'
    '<xf numFmtId="0" fontId="4" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf>'
    '<xf numFmtId="0" fontId="5" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf>'
    '<xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf>'
    '<xf numFmtId="0" fontId="0" fillId="3" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf>'
    '<xf numFmtId="164" fontId="0" fillId="0" borderId="1" xfId="0" applyNumberFormat="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="top"/></xf>'
    '<xf numFmtId="164" fontId="0" fillId="3" borderId="1" xfId="0" applyNumberFormat="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="left" vertical="top"/></xf>'
    '<xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="top"/></xf>'
    '<xf numFmtId="0" fontId="0" fillId="3" borderId="1" xfId="0" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center" vertical="top"/></xf>'
    '</cellXfs>'
    '<cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles>'
    '</styleSheet>';

// =============================================================================
// Word — landscape, narrow margins, 7 pt, bold heading row on every page.
// =============================================================================

Uint8List buildRegisterDocx(ExportTable t) {
  // A4 landscape in twips with 1 cm margins.
  const pageW = 16838, pageH = 11906, margin = 567;
  const usable = pageW - 2 * margin;

  final columns = t.numberedColumns;
  final totalFlex = columns.fold<double>(0, (sum, c) => sum + c.flex);
  final widths = [
    for (final c in columns) (usable * c.flex / totalFlex).floor(),
  ];

  String run(String text, {int size = 14, bool bold = false, String? color}) =>
      '<w:r><w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial" w:cs="Arial"/>'
      '${bold ? '<w:b/>' : ''}${color == null ? '' : '<w:color w:val="$color"/>'}'
      '<w:sz w:val="$size"/><w:szCs w:val="$size"/></w:rPr>'
      '<w:t xml:space="preserve">${_xmlEsc(text)}</w:t></w:r>';
  String para(String text,
          {int size = 14, bool bold = false, String? color, String align = 'left', int after = 0}) =>
      '<w:p><w:pPr><w:spacing w:before="0" w:after="$after"/><w:jc w:val="$align"/></w:pPr>'
      '${run(text, size: size, bold: bold, color: color)}</w:p>';
  String cell(String text, int width,
          {bool header = false, String? fill, String align = 'left'}) =>
      '<w:tc><w:tcPr><w:tcW w:w="$width" w:type="dxa"/>'
      '${fill == null ? '' : '<w:shd w:val="clear" w:color="auto" w:fill="$fill"/>'}'
      '<w:vAlign w:val="${header ? 'center' : 'top'}"/></w:tcPr>'
      '<w:p><w:pPr><w:spacing w:before="20" w:after="20"/><w:jc w:val="$align"/></w:pPr>'
      '${run(text, size: header ? 13 : 14, bold: header, color: header ? 'FFFFFF' : null)}'
      '</w:p></w:tc>';

  const border = 'w:val="single" w:sz="4" w:space="0" w:color="$_lineHex"';
  final table = StringBuffer()
    ..write('<w:tbl><w:tblPr><w:tblW w:w="$usable" w:type="dxa"/>'
        '<w:tblBorders><w:top $border/><w:left $border/><w:bottom $border/>'
        '<w:right $border/><w:insideH $border/><w:insideV $border/></w:tblBorders>'
        '<w:tblLayout w:type="fixed"/>'
        '<w:tblCellMar><w:left w:w="45" w:type="dxa"/><w:right w:w="45" w:type="dxa"/></w:tblCellMar>'
        '</w:tblPr><w:tblGrid>')
    ..writeAll([for (final w in widths) '<w:gridCol w:w="$w"/>'])
    ..write('</w:tblGrid>')
    // Bold heading row, repeated at the top of every page.
    ..write('<w:tr><w:trPr><w:tblHeader/><w:cantSplit/></w:trPr>')
    ..writeAll([
      for (var i = 0; i < columns.length; i++)
        cell(columns[i].title, widths[i],
            header: true, fill: _primaryHex, align: i == 0 ? 'center' : 'left'),
    ])
    ..write('</w:tr>');
  final rows = t.numberedRows;
  for (var r = 0; r < rows.length; r++) {
    table.write('<w:tr><w:trPr><w:cantSplit/></w:trPr>');
    for (var i = 0; i < columns.length; i++) {
      table.write(cell(rows[r][i], widths[i],
          fill: r.isOdd ? _stripeHex : null, align: i == 0 ? 'center' : 'left'));
    }
    table.write('</w:tr>');
  }
  table.write('</w:tbl>');

  final info = [
    if (t.filters.isNotEmpty) t.filterLine,
    'Printed: ${t.dateText}',
    t.totalText,
  ].join('     |     ');

  final document = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
      'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
      '<w:body>'
      '${para(t.schoolName.trim().toUpperCase(), size: 30, bold: true, color: _primaryHex, align: 'center')}'
      '${t.schoolAddress.trim().isEmpty ? '' : para(t.schoolAddress.trim(), size: 17, align: 'center')}'
      '${para(_heading(t), size: 24, bold: true, align: 'center', after: 20)}'
      '${para(info, size: 15, color: _mutedHex, align: 'center', after: 100)}'
      '$table'
      '${t.rows.isEmpty ? para('No pupils match these filters.', size: 18, color: _mutedHex, align: 'center') : ''}'
      '<w:sectPr><w:footerReference w:type="default" r:id="rIdFooter1"/>'
      '<w:pgSz w:w="$pageW" w:h="$pageH" w:orient="landscape"/>'
      '<w:pgMar w:top="$margin" w:right="$margin" w:bottom="$margin" w:left="$margin" '
      'w:header="340" w:footer="340" w:gutter="0"/></w:sectPr>'
      '</w:body></w:document>';

  // Footer: "Generated by Evangelist Global" and the page number.
  final footer = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
      '<w:p><w:pPr><w:tabs><w:tab w:val="right" w:pos="$usable"/></w:tabs>'
      '<w:spacing w:before="0" w:after="0"/></w:pPr>'
      '${run('Generated by Evangelist Global', size: 14, color: _mutedHex)}'
      '<w:r><w:tab/></w:r>${run('Page ', size: 14, color: _mutedHex)}'
      '<w:fldSimple w:instr=" PAGE ">${run('1', size: 14, color: _mutedHex)}</w:fldSimple>'
      '</w:p></w:ftr>';

  final archive = Archive();
  void add(String name, String xml) {
    final bytes = utf8.encode(xml);
    archive.addFile(ArchiveFile(name, bytes.length, bytes));
  }

  add('[Content_Types].xml',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
      '<Default Extension="xml" ContentType="application/xml"/>'
      '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
      '<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>'
      '</Types>');
  add('_rels/.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
      '</Relationships>');
  add('word/_rels/document.xml.rels',
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
      '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
      '<Relationship Id="rIdFooter1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>'
      '</Relationships>');
  add('word/document.xml', document);
  add('word/footer1.xml', footer);
  return Uint8List.fromList(ZipEncoder().encode(archive)!);
}
