import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../models/student.dart';

/// One line of a student's promotion history, already in words.
class HistoryLine {
  const HistoryLine({
    required this.year,
    required this.from,
    required this.to,
    required this.outcome,
    required this.date,
  });

  final String year;
  final String from;
  final String to;
  final String outcome;
  final String date;
}

/// Everything the student record PDF prints. Images are raw JPG/PNG bytes;
/// any of them may be missing.
class StudentRecordData {
  const StudentRecordData({
    required this.student,
    required this.className,
    required this.history,
    required this.schoolName,
    required this.exportedAt,
    this.historyVisible = true,
    this.schoolAddress = '',
    this.schoolPhone = '',
    this.schoolEmail = '',
    this.headName = '',
    this.badge,
    this.stamp,
    this.photo,
  });

  final Student student;
  final String className;
  final List<HistoryLine> history;

  /// False for users who may not read promotion history (teachers).
  final bool historyVisible;
  final String schoolName;
  final String schoolAddress;
  final String schoolPhone;
  final String schoolEmail;

  /// Head Teacher / Principal, printed under the signature line.
  final String headName;
  final Uint8List? badge;
  final Uint8List? stamp;
  final Uint8List? photo;
  final DateTime exportedAt;
}

/// Brand colours (see `AppColors`), repeated here because the pdf package
/// has its own colour type.
final _primary = PdfColor.fromHex('#2E3192');
final _band = PdfColor.fromHex('#E8E9F6');
final _line = PdfColor.fromHex('#C5C8D6');
final _muted = PdfColor.fromHex('#5E6470');

final _date = DateFormat('d MMMM yyyy');
final _dateTime = DateFormat('d MMMM yyyy, h:mm a');
final _short = DateFormat('d MMM yyyy');

/// The built-in PDF font covers Latin-1 only; anything else would print as a
/// blank box, so it is replaced with "?".
String _safe(String s) =>
    String.fromCharCodes(s.runes.map((r) => r <= 0xFF ? r : 0x3F));

String _or(String s) => s.trim().isEmpty ? '-' : s.trim();

/// A4 "STUDENT INFORMATION RECORD": school letterhead, the student's photo
/// and every field on the record, promotion history, the certification
/// paragraph, signature line and stamp, and a numbered footer.
Future<Uint8List> buildStudentRecordPdf(StudentRecordData d) async {
  final s = d.student;
  final doc = pw.Document(
    title: _safe('Student record - ${s.fullName}'),
    author: _safe(d.schoolName),
    creator: 'Evangelist Global',
  );
  pw.ImageProvider? image(Uint8List? bytes) {
    if (bytes == null) return null;
    try {
      return pw.MemoryImage(bytes);
    } catch (_) {
      return null; // An unreadable image is left out, not fatal.
    }
  }

  final badge = image(d.badge);
  final stamp = image(d.stamp);
  final photo = image(d.photo);
  final exported = _safe(_dateTime.format(d.exportedAt));

  doc.addPage(pw.MultiPage(
    pageFormat: PdfPageFormat.a4,
    margin: const pw.EdgeInsets.fromLTRB(36, 32, 36, 28),
    footer: (context) => pw.Container(
      margin: const pw.EdgeInsets.only(top: 10),
      padding: const pw.EdgeInsets.only(top: 4),
      decoration: pw.BoxDecoration(
          border: pw.Border(top: pw.BorderSide(color: _line, width: 0.5))),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Evangelist Global on $exported',
              style: pw.TextStyle(fontSize: 8, color: _muted)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(fontSize: 8, color: _muted)),
        ],
      ),
    ),
    build: (context) => [
      _letterhead(d, badge),
      pw.SizedBox(height: 14),
      pw.Center(
        child: pw.Text('STUDENT INFORMATION RECORD',
            style: pw.TextStyle(
                fontSize: 15,
                fontWeight: pw.FontWeight.bold,
                letterSpacing: 1.5,
                color: _primary)),
      ),
      pw.SizedBox(height: 14),
      _summary(d, photo),
      pw.SizedBox(height: 12),
      _section('PERSONAL INFORMATION', [
        ('First name', s.firstName),
        ('Middle name', s.middleName),
        ('Last name', s.lastName),
        ('Gender', s.gender.isEmpty
            ? ''
            : s.gender[0].toUpperCase() + s.gender.substring(1)),
        ('Date of birth', s.dob == null ? '' : _short.format(s.dob!)),
        ('Home address', s.address),
      ]),
      _section('GUARDIAN / CONTACT', [
        ('Guardian name', s.guardianName),
        ('Guardian phone', s.guardianPhone),
      ]),
      _section('ACADEMIC INFORMATION', [
        ('Student ID', s.admissionNo),
        ('Level', s.level?.label ?? ''),
        ('Class', d.className),
        ('Department', s.department ?? ''),
        ('Admission year', s.admissionYear),
        ('Date registered',
            s.createdAt == null ? '' : _short.format(s.createdAt!)),
        ('Status', StudentStatus.label(s.status)),
        ('Last promoted', s.lastPromotedAt == null
            ? 'Not yet promoted'
            : _short.format(s.lastPromotedAt!)),
      ]),
      _section('EXAM RECORDS', [
        ('NPSE index no.', s.npseId),
        ('NPSE year', s.npseYear),
        ('BECE index no.', s.beceId),
        ('BECE year', s.beceYear),
        ('WASSCE index no.', s.wassceId),
        ('WASSCE year', s.wassceYear),
      ]),
      if (d.historyVisible) _history(d.history),
      pw.SizedBox(height: 6),
      _certification(d, exported),
      pw.SizedBox(height: 28),
      _signatures(d, stamp),
    ],
  ));
  return doc.save();
}

pw.Widget _letterhead(StudentRecordData d, pw.ImageProvider? badge) {
  final contact = [
    if (d.schoolPhone.trim().isNotEmpty) 'Tel: ${d.schoolPhone.trim()}',
    if (d.schoolEmail.trim().isNotEmpty) 'Email: ${d.schoolEmail.trim()}',
  ].join('   |   ');
  return pw.Column(
    children: [
      pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          if (badge != null)
            pw.SizedBox(
                width: 70,
                height: 70,
                child: pw.Image(badge, fit: pw.BoxFit.contain))
          else
            pw.SizedBox(width: 70),
          pw.SizedBox(width: 12),
          pw.Expanded(
            child: pw.Column(
              children: [
                pw.Text(_safe(d.schoolName.toUpperCase()),
                    textAlign: pw.TextAlign.center,
                    style: pw.TextStyle(
                        fontSize: 20,
                        fontWeight: pw.FontWeight.bold,
                        color: _primary)),
                if (d.schoolAddress.trim().isNotEmpty) ...[
                  pw.SizedBox(height: 3),
                  pw.Text(_safe(d.schoolAddress.trim()),
                      textAlign: pw.TextAlign.center,
                      style: const pw.TextStyle(fontSize: 10)),
                ],
                if (contact.isNotEmpty) ...[
                  pw.SizedBox(height: 2),
                  pw.Text(_safe(contact),
                      textAlign: pw.TextAlign.center,
                      style: pw.TextStyle(fontSize: 9, color: _muted)),
                ],
              ],
            ),
          ),
          pw.SizedBox(width: 12),
          // Balances the badge so the name stays centred on the page.
          pw.SizedBox(width: 70),
        ],
      ),
      pw.SizedBox(height: 10),
      pw.Divider(color: _primary, thickness: 2, height: 2),
      pw.SizedBox(height: 2),
      pw.Divider(color: _primary, thickness: 0.5, height: 0.5),
    ],
  );
}

pw.Widget _summary(StudentRecordData d, pw.ImageProvider? photo) {
  final s = d.student;
  pw.Widget line(String label, String value) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: pw.RichText(
          text: pw.TextSpan(children: [
            pw.TextSpan(
                text: '$label:  ',
                style: pw.TextStyle(fontSize: 10, color: _muted)),
            pw.TextSpan(
                text: _safe(_or(value)),
                style: pw.TextStyle(
                    fontSize: 11, fontWeight: pw.FontWeight.bold)),
          ]),
        ),
      );
  return pw.Row(
    crossAxisAlignment: pw.CrossAxisAlignment.start,
    children: [
      pw.Container(
        width: 96,
        height: 116,
        decoration: pw.BoxDecoration(
            border: pw.Border.all(color: _line), color: _band),
        child: photo != null
            ? pw.Image(photo, fit: pw.BoxFit.cover)
            : pw.Center(
                child: pw.Text('No photo',
                    style: pw.TextStyle(fontSize: 9, color: _muted))),
      ),
      pw.SizedBox(width: 16),
      pw.Expanded(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(_safe(s.fullName),
                style: pw.TextStyle(
                    fontSize: 17, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            line('Student ID', s.admissionNo),
            line('Class', d.className),
            line('Status', StudentStatus.label(s.status)),
            line('Level', s.level?.label ?? ''),
          ],
        ),
      ),
    ],
  );
}

/// A banded heading, then label / value pairs two to a row.
pw.Widget _section(String title, List<(String, String)> rows) {
  final cells = <pw.TableRow>[];
  for (var i = 0; i < rows.length; i += 2) {
    final pair = rows.sublist(i, i + 2 > rows.length ? rows.length : i + 2);
    cells.add(pw.TableRow(children: [
      for (final (label, value) in pair) ...[
        _cell(label, muted: true),
        _cell(_or(value), bold: true),
      ],
      if (pair.length == 1) ...[_cell(''), _cell('')],
    ]));
  }
  return pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 10),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        _sectionBand(title),
        pw.Table(
          border: pw.TableBorder.all(color: _line, width: 0.5),
          columnWidths: const {
            0: pw.FlexColumnWidth(1.1),
            1: pw.FlexColumnWidth(1.6),
            2: pw.FlexColumnWidth(1.1),
            3: pw.FlexColumnWidth(1.6),
          },
          children: cells,
        ),
      ],
    ),
  );
}

pw.Widget _history(List<HistoryLine> history) {
  final header = ['Year', 'From class', 'To class', 'Result', 'Date'];
  return pw.Padding(
    padding: const pw.EdgeInsets.only(bottom: 10),
    child: pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        _sectionBand('PROMOTION HISTORY'),
        if (history.isEmpty)
          pw.Container(
            padding: const pw.EdgeInsets.all(6),
            decoration: pw.BoxDecoration(
                border: pw.Border.all(color: _line, width: 0.5)),
            child: pw.Text('No promotions recorded yet.',
                style: pw.TextStyle(fontSize: 9, color: _muted)),
          )
        else
          pw.Table(
            border: pw.TableBorder.all(color: _line, width: 0.5),
            children: [
              pw.TableRow(
                decoration: pw.BoxDecoration(color: _band),
                children: [for (final h in header) _cell(h, bold: true)],
              ),
              for (final h in history)
                pw.TableRow(children: [
                  _cell(_or(h.year)),
                  _cell(_or(h.from)),
                  _cell(_or(h.to)),
                  _cell(h.outcome, bold: true),
                  _cell(_or(h.date)),
                ]),
            ],
          ),
      ],
    ),
  );
}

pw.Widget _certification(StudentRecordData d, String exported) {
  final s = d.student;
  final school = d.schoolAddress.trim().isEmpty
      ? d.schoolName.trim()
      : '${d.schoolName.trim()}, ${d.schoolAddress.trim()}';
  final text = 'This is to certify that ${s.fullName}, Student ID '
      '${_or(s.admissionNo)}, is a bona fide student of $school. The '
      'information contained in this document is correct and accurate '
      "according to the school's records as at $exported.";
  return pw.Container(
    padding: const pw.EdgeInsets.all(10),
    decoration: pw.BoxDecoration(
      border: pw.Border.all(color: _primary, width: 0.8),
      borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
    ),
    child: pw.Text(_safe(text),
        textAlign: pw.TextAlign.justify,
        style: const pw.TextStyle(fontSize: 10.5, lineSpacing: 3)),
  );
}

pw.Widget _signatures(StudentRecordData d, pw.ImageProvider? stamp) {
  return pw.Row(
    crossAxisAlignment: pw.CrossAxisAlignment.end,
    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
    children: [
      pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(width: 190, height: 0.8, color: PdfColors.black),
          pw.SizedBox(height: 4),
          pw.Text('Head Teacher / Principal',
              style: pw.TextStyle(
                  fontSize: 10, fontWeight: pw.FontWeight.bold)),
          if (d.headName.trim().isNotEmpty)
            pw.Text(_safe(d.headName.trim()),
                style: const pw.TextStyle(fontSize: 10)),
          pw.SizedBox(height: 6),
          pw.Text(_safe('Date: ${_date.format(d.exportedAt)}'),
              style: const pw.TextStyle(fontSize: 10)),
        ],
      ),
      stamp != null
          ? pw.SizedBox(
              width: 110,
              height: 110,
              child: pw.Image(stamp, fit: pw.BoxFit.contain))
          : pw.Container(
              width: 110,
              height: 110,
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: _line, width: 1),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(55)),
              ),
              child: pw.Center(
                child: pw.Text('School Stamp',
                    style: pw.TextStyle(fontSize: 9, color: _muted)),
              ),
            ),
    ],
  );
}

pw.Widget _sectionBand(String title) => pw.Container(
      color: _primary,
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 3),
      child: pw.Text(title,
          style: pw.TextStyle(
              color: PdfColors.white,
              fontSize: 9.5,
              fontWeight: pw.FontWeight.bold,
              letterSpacing: 0.8)),
    );

pw.Widget _cell(String text, {bool bold = false, bool muted = false}) =>
    pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 4),
      child: pw.Text(_safe(text),
          style: pw.TextStyle(
            fontSize: 9.5,
            fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
            color: muted ? _muted : null,
          )),
    );

extension on StudentRecordData {
  /// The same record with no images, for when an image can't be decoded.
  StudentRecordData withoutImages() => StudentRecordData(
        student: student,
        className: className,
        history: history,
        historyVisible: historyVisible,
        schoolName: schoolName,
        schoolAddress: schoolAddress,
        schoolPhone: schoolPhone,
        schoolEmail: schoolEmail,
        headName: headName,
        exportedAt: exportedAt,
      );
}

/// [buildStudentRecordPdf], falling back to a copy without images if one of
/// them is corrupt or in a format the PDF can't hold — an export should
/// never fail just because of a picture.
Future<Uint8List> buildStudentRecordPdfSafely(StudentRecordData d) async {
  try {
    return await buildStudentRecordPdf(d);
  } catch (_) {
    return buildStudentRecordPdf(d.withoutImages());
  }
}
